name: Write sample sbom and verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node modules
        run: npm ci

      - name: Build example workflow
        run: npm run build-examples

      - name: Create sample SBOM
        run: npm run create-sample-sbom

      - name: Install spdx-tools-java
        run: .github/workflows/scripts/spdx-tools-java-wrapper.sh bootstrap

      - name: Verify SBOM
        run: .github/workflows/scripts/verify.sh lib/examples/resources/sample.sbom.json
